var pacs008_Module_Factory = function () {
  var pacs008 = {
    name: 'pacs008',
    defaultElementNamespaceURI: 'urn:iso:std:iso:20022:tech:xsd:pacs.008.001.07',
    typeInfos: [{
        localName: 'LocalInstrument2Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'ReferredDocumentInformation7',
        propertyInfos: [{
            name: 'tp',
            elementName: 'Tp',
            typeInfo: '.ReferredDocumentType4'
          }, {
            name: 'nb',
            elementName: 'Nb'
          }, {
            name: 'rltdDt',
            elementName: 'RltdDt',
            typeInfo: 'Date'
          }, {
            name: 'lineDtls',
            minOccurs: 0,
            collection: true,
            elementName: 'LineDtls',
            typeInfo: '.DocumentLineInformation1'
          }]
      }, {
        localName: 'InstructionForNextAgent1',
        propertyInfos: [{
            name: 'cd',
            elementName: 'Cd'
          }, {
            name: 'instrInf',
            elementName: 'InstrInf'
          }]
      }, {
        localName: 'TaxParty2',
        propertyInfos: [{
            name: 'taxId',
            elementName: 'TaxId'
          }, {
            name: 'regnId',
            elementName: 'RegnId'
          }, {
            name: 'taxTp',
            elementName: 'TaxTp'
          }, {
            name: 'authstn',
            elementName: 'Authstn',
            typeInfo: '.TaxAuthorisation1'
          }]
      }, {
        localName: 'CreditTransferTransaction30',
        propertyInfos: [{
            name: 'pmtId',
            required: true,
            elementName: 'PmtId',
            typeInfo: '.PaymentIdentification3'
          }, {
            name: 'pmtTpInf',
            elementName: 'PmtTpInf',
            typeInfo: '.PaymentTypeInformation21'
          }, {
            name: 'intrBkSttlmAmt',
            required: true,
            elementName: 'IntrBkSttlmAmt',
            typeInfo: '.ActiveCurrencyAndAmount'
          }, {
            name: 'intrBkSttlmDt',
            elementName: 'IntrBkSttlmDt',
            typeInfo: 'Date'
          }, {
            name: 'sttlmPrty',
            elementName: 'SttlmPrty'
          }, {
            name: 'sttlmTmIndctn',
            elementName: 'SttlmTmIndctn',
            typeInfo: '.SettlementDateTimeIndication1'
          }, {
            name: 'sttlmTmReq',
            elementName: 'SttlmTmReq',
            typeInfo: '.SettlementTimeRequest2'
          }, {
            name: 'accptncDtTm',
            elementName: 'AccptncDtTm',
            typeInfo: 'DateTime'
          }, {
            name: 'poolgAdjstmntDt',
            elementName: 'PoolgAdjstmntDt',
            typeInfo: 'Date'
          }, {
            name: 'instdAmt',
            elementName: 'InstdAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'xchgRate',
            elementName: 'XchgRate',
            typeInfo: 'Decimal'
          }, {
            name: 'chrgBr',
            required: true,
            elementName: 'ChrgBr'
          }, {
            name: 'chrgsInf',
            minOccurs: 0,
            collection: true,
            elementName: 'ChrgsInf',
            typeInfo: '.Charges2'
          }, {
            name: 'prvsInstgAgt1',
            elementName: 'PrvsInstgAgt1',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'prvsInstgAgt1Acct',
            elementName: 'PrvsInstgAgt1Acct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'prvsInstgAgt2',
            elementName: 'PrvsInstgAgt2',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'prvsInstgAgt2Acct',
            elementName: 'PrvsInstgAgt2Acct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'prvsInstgAgt3',
            elementName: 'PrvsInstgAgt3',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'prvsInstgAgt3Acct',
            elementName: 'PrvsInstgAgt3Acct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'instgAgt',
            elementName: 'InstgAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'instdAgt',
            elementName: 'InstdAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'intrmyAgt1',
            elementName: 'IntrmyAgt1',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'intrmyAgt1Acct',
            elementName: 'IntrmyAgt1Acct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'intrmyAgt2',
            elementName: 'IntrmyAgt2',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'intrmyAgt2Acct',
            elementName: 'IntrmyAgt2Acct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'intrmyAgt3',
            elementName: 'IntrmyAgt3',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'intrmyAgt3Acct',
            elementName: 'IntrmyAgt3Acct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'ultmtDbtr',
            elementName: 'UltmtDbtr',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'initgPty',
            elementName: 'InitgPty',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'dbtr',
            required: true,
            elementName: 'Dbtr',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'dbtrAcct',
            elementName: 'DbtrAcct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'dbtrAgt',
            required: true,
            elementName: 'DbtrAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'dbtrAgtAcct',
            elementName: 'DbtrAgtAcct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'cdtrAgt',
            required: true,
            elementName: 'CdtrAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'cdtrAgtAcct',
            elementName: 'CdtrAgtAcct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'cdtr',
            required: true,
            elementName: 'Cdtr',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'cdtrAcct',
            elementName: 'CdtrAcct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'ultmtCdtr',
            elementName: 'UltmtCdtr',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'instrForCdtrAgt',
            minOccurs: 0,
            collection: true,
            elementName: 'InstrForCdtrAgt',
            typeInfo: '.InstructionForCreditorAgent1'
          }, {
            name: 'instrForNxtAgt',
            minOccurs: 0,
            collection: true,
            elementName: 'InstrForNxtAgt',
            typeInfo: '.InstructionForNextAgent1'
          }, {
            name: 'purp',
            elementName: 'Purp',
            typeInfo: '.Purpose2Choice'
          }, {
            name: 'rgltryRptg',
            minOccurs: 0,
            maxOccurs: 10,
            collection: true,
            elementName: 'RgltryRptg',
            typeInfo: '.RegulatoryReporting3'
          }, {
            name: 'tax',
            elementName: 'Tax',
            typeInfo: '.TaxInformation6'
          }, {
            name: 'rltdRmtInf',
            minOccurs: 0,
            maxOccurs: 10,
            collection: true,
            elementName: 'RltdRmtInf',
            typeInfo: '.RemittanceLocation4'
          }, {
            name: 'rmtInf',
            elementName: 'RmtInf',
            typeInfo: '.RemittanceInformation15'
          }, {
            name: 'splmtryData',
            minOccurs: 0,
            collection: true,
            elementName: 'SplmtryData',
            typeInfo: '.SupplementaryData1'
          }]
      }, {
        localName: 'GenericPersonIdentification1',
        propertyInfos: [{
            name: 'id',
            required: true,
            elementName: 'Id'
          }, {
            name: 'schmeNm',
            elementName: 'SchmeNm',
            typeInfo: '.PersonIdentificationSchemeName1Choice'
          }, {
            name: 'issr',
            elementName: 'Issr'
          }]
      }, {
        localName: 'PaymentIdentification3',
        propertyInfos: [{
            name: 'instrId',
            elementName: 'InstrId'
          }, {
            name: 'endToEndId',
            required: true,
            elementName: 'EndToEndId'
          }, {
            name: 'txId',
            required: true,
            elementName: 'TxId'
          }, {
            name: 'clrSysRef',
            elementName: 'ClrSysRef'
          }]
      }, {
        localName: 'AccountIdentification4Choice',
        propertyInfos: [{
            name: 'iban',
            required: true,
            elementName: 'IBAN'
          }, {
            name: 'othr',
            required: true,
            elementName: 'Othr',
            typeInfo: '.GenericAccountIdentification1'
          }]
      }, {
        localName: 'CashAccount24',
        propertyInfos: [{
            name: 'id',
            required: true,
            elementName: 'Id',
            typeInfo: '.AccountIdentification4Choice'
          }, {
            name: 'tp',
            elementName: 'Tp',
            typeInfo: '.CashAccountType2Choice'
          }, {
            name: 'ccy',
            elementName: 'Ccy'
          }, {
            name: 'nm',
            elementName: 'Nm'
          }]
      }, {
        localName: 'GroupHeader70',
        propertyInfos: [{
            name: 'msgId',
            required: true,
            elementName: 'MsgId'
          }, {
            name: 'creDtTm',
            required: true,
            elementName: 'CreDtTm',
            typeInfo: 'DateTime'
          }, {
            name: 'btchBookg',
            elementName: 'BtchBookg',
            typeInfo: 'Boolean'
          }, {
            name: 'nbOfTxs',
            required: true,
            elementName: 'NbOfTxs'
          }, {
            name: 'ctrlSum',
            elementName: 'CtrlSum',
            typeInfo: 'Decimal'
          }, {
            name: 'ttlIntrBkSttlmAmt',
            elementName: 'TtlIntrBkSttlmAmt',
            typeInfo: '.ActiveCurrencyAndAmount'
          }, {
            name: 'intrBkSttlmDt',
            elementName: 'IntrBkSttlmDt',
            typeInfo: 'Date'
          }, {
            name: 'sttlmInf',
            required: true,
            elementName: 'SttlmInf',
            typeInfo: '.SettlementInstruction4'
          }, {
            name: 'pmtTpInf',
            elementName: 'PmtTpInf',
            typeInfo: '.PaymentTypeInformation21'
          }, {
            name: 'instgAgt',
            elementName: 'InstgAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'instdAgt',
            elementName: 'InstdAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }]
      }, {
        localName: 'RemittanceLocationDetails1',
        propertyInfos: [{
            name: 'mtd',
            required: true,
            elementName: 'Mtd'
          }, {
            name: 'elctrncAdr',
            elementName: 'ElctrncAdr'
          }, {
            name: 'pstlAdr',
            elementName: 'PstlAdr',
            typeInfo: '.NameAndAddress10'
          }]
      }, {
        localName: 'ActiveOrHistoricCurrencyAndAmount',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Decimal',
            type: 'value'
          }, {
            name: 'ccy',
            required: true,
            attributeName: {
              localPart: 'Ccy'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'RemittanceAmount3',
        propertyInfos: [{
            name: 'duePyblAmt',
            elementName: 'DuePyblAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'dscntApldAmt',
            minOccurs: 0,
            collection: true,
            elementName: 'DscntApldAmt',
            typeInfo: '.DiscountAmountAndType1'
          }, {
            name: 'cdtNoteAmt',
            elementName: 'CdtNoteAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'taxAmt',
            minOccurs: 0,
            collection: true,
            elementName: 'TaxAmt',
            typeInfo: '.TaxAmountAndType1'
          }, {
            name: 'adjstmntAmtAndRsn',
            minOccurs: 0,
            collection: true,
            elementName: 'AdjstmntAmtAndRsn',
            typeInfo: '.DocumentAdjustment1'
          }, {
            name: 'rmtdAmt',
            elementName: 'RmtdAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }]
      }, {
        localName: 'AccountSchemeName1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'PaymentTypeInformation21',
        propertyInfos: [{
            name: 'instrPrty',
            elementName: 'InstrPrty'
          }, {
            name: 'clrChanl',
            elementName: 'ClrChanl'
          }, {
            name: 'svcLvl',
            elementName: 'SvcLvl',
            typeInfo: '.ServiceLevel8Choice'
          }, {
            name: 'lclInstrm',
            elementName: 'LclInstrm',
            typeInfo: '.LocalInstrument2Choice'
          }, {
            name: 'ctgyPurp',
            elementName: 'CtgyPurp',
            typeInfo: '.CategoryPurpose1Choice'
          }]
      }, {
        localName: 'PartyIdentification125',
        propertyInfos: [{
            name: 'nm',
            elementName: 'Nm'
          }, {
            name: 'pstlAdr',
            elementName: 'PstlAdr',
            typeInfo: '.PostalAddress6'
          }, {
            name: 'id',
            elementName: 'Id',
            typeInfo: '.Party34Choice'
          }, {
            name: 'ctryOfRes',
            elementName: 'CtryOfRes'
          }, {
            name: 'ctctDtls',
            elementName: 'CtctDtls',
            typeInfo: '.ContactDetails2'
          }]
      }, {
        localName: 'TaxPeriod2',
        propertyInfos: [{
            name: 'yr',
            elementName: 'Yr',
            typeInfo: 'Date'
          }, {
            name: 'tp',
            elementName: 'Tp'
          }, {
            name: 'frToDt',
            elementName: 'FrToDt',
            typeInfo: '.DatePeriod2'
          }]
      }, {
        localName: 'TaxInformation7',
        propertyInfos: [{
            name: 'cdtr',
            elementName: 'Cdtr',
            typeInfo: '.TaxParty1'
          }, {
            name: 'dbtr',
            elementName: 'Dbtr',
            typeInfo: '.TaxParty2'
          }, {
            name: 'ultmtDbtr',
            elementName: 'UltmtDbtr',
            typeInfo: '.TaxParty2'
          }, {
            name: 'admstnZone',
            elementName: 'AdmstnZone'
          }, {
            name: 'refNb',
            elementName: 'RefNb'
          }, {
            name: 'mtd',
            elementName: 'Mtd'
          }, {
            name: 'ttlTaxblBaseAmt',
            elementName: 'TtlTaxblBaseAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'ttlTaxAmt',
            elementName: 'TtlTaxAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'dt',
            elementName: 'Dt',
            typeInfo: 'Date'
          }, {
            name: 'seqNb',
            elementName: 'SeqNb',
            typeInfo: 'Decimal'
          }, {
            name: 'rcrd',
            minOccurs: 0,
            collection: true,
            elementName: 'Rcrd',
            typeInfo: '.TaxRecord2'
          }]
      }, {
        localName: 'DatePeriod2',
        propertyInfos: [{
            name: 'frDt',
            required: true,
            elementName: 'FrDt',
            typeInfo: 'Date'
          }, {
            name: 'toDt',
            required: true,
            elementName: 'ToDt',
            typeInfo: 'Date'
          }]
      }, {
        localName: 'TaxAmountType1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'RemittanceAmount2',
        propertyInfos: [{
            name: 'duePyblAmt',
            elementName: 'DuePyblAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'dscntApldAmt',
            minOccurs: 0,
            collection: true,
            elementName: 'DscntApldAmt',
            typeInfo: '.DiscountAmountAndType1'
          }, {
            name: 'cdtNoteAmt',
            elementName: 'CdtNoteAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'taxAmt',
            minOccurs: 0,
            collection: true,
            elementName: 'TaxAmt',
            typeInfo: '.TaxAmountAndType1'
          }, {
            name: 'adjstmntAmtAndRsn',
            minOccurs: 0,
            collection: true,
            elementName: 'AdjstmntAmtAndRsn',
            typeInfo: '.DocumentAdjustment1'
          }, {
            name: 'rmtdAmt',
            elementName: 'RmtdAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }]
      }, {
        localName: 'PersonIdentificationSchemeName1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'RemittanceInformation15',
        propertyInfos: [{
            name: 'ustrd',
            minOccurs: 0,
            collection: true,
            elementName: 'Ustrd'
          }, {
            name: 'strd',
            minOccurs: 0,
            collection: true,
            elementName: 'Strd',
            typeInfo: '.StructuredRemittanceInformation15'
          }]
      }, {
        localName: 'ReferredDocumentType4',
        propertyInfos: [{
            name: 'cdOrPrtry',
            required: true,
            elementName: 'CdOrPrtry',
            typeInfo: '.ReferredDocumentType3Choice'
          }, {
            name: 'issr',
            elementName: 'Issr'
          }]
      }, {
        localName: 'DiscountAmountAndType1',
        propertyInfos: [{
            name: 'tp',
            elementName: 'Tp',
            typeInfo: '.DiscountAmountType1Choice'
          }, {
            name: 'amt',
            required: true,
            elementName: 'Amt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }]
      }, {
        localName: 'OrganisationIdentification8',
        propertyInfos: [{
            name: 'anyBIC',
            elementName: 'AnyBIC'
          }, {
            name: 'othr',
            minOccurs: 0,
            collection: true,
            elementName: 'Othr',
            typeInfo: '.GenericOrganisationIdentification1'
          }]
      }, {
        localName: 'TaxAmountAndType1',
        propertyInfos: [{
            name: 'tp',
            elementName: 'Tp',
            typeInfo: '.TaxAmountType1Choice'
          }, {
            name: 'amt',
            required: true,
            elementName: 'Amt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }]
      }, {
        localName: 'SettlementInstruction4',
        propertyInfos: [{
            name: 'sttlmMtd',
            required: true,
            elementName: 'SttlmMtd'
          }, {
            name: 'sttlmAcct',
            elementName: 'SttlmAcct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'clrSys',
            elementName: 'ClrSys',
            typeInfo: '.ClearingSystemIdentification3Choice'
          }, {
            name: 'instgRmbrsmntAgt',
            elementName: 'InstgRmbrsmntAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'instgRmbrsmntAgtAcct',
            elementName: 'InstgRmbrsmntAgtAcct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'instdRmbrsmntAgt',
            elementName: 'InstdRmbrsmntAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'instdRmbrsmntAgtAcct',
            elementName: 'InstdRmbrsmntAgtAcct',
            typeInfo: '.CashAccount24'
          }, {
            name: 'thrdRmbrsmntAgt',
            elementName: 'ThrdRmbrsmntAgt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }, {
            name: 'thrdRmbrsmntAgtAcct',
            elementName: 'ThrdRmbrsmntAgtAcct',
            typeInfo: '.CashAccount24'
          }]
      }, {
        localName: 'ClearingSystemIdentification3Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'PersonIdentification13',
        propertyInfos: [{
            name: 'dtAndPlcOfBirth',
            elementName: 'DtAndPlcOfBirth',
            typeInfo: '.DateAndPlaceOfBirth1'
          }, {
            name: 'othr',
            minOccurs: 0,
            collection: true,
            elementName: 'Othr',
            typeInfo: '.GenericPersonIdentification1'
          }]
      }, {
        localName: 'PostalAddress6',
        propertyInfos: [{
            name: 'adrTp',
            elementName: 'AdrTp'
          }, {
            name: 'dept',
            elementName: 'Dept'
          }, {
            name: 'subDept',
            elementName: 'SubDept'
          }, {
            name: 'strtNm',
            elementName: 'StrtNm'
          }, {
            name: 'bldgNb',
            elementName: 'BldgNb'
          }, {
            name: 'pstCd',
            elementName: 'PstCd'
          }, {
            name: 'twnNm',
            elementName: 'TwnNm'
          }, {
            name: 'ctrySubDvsn',
            elementName: 'CtrySubDvsn'
          }, {
            name: 'ctry',
            elementName: 'Ctry'
          }, {
            name: 'adrLine',
            minOccurs: 0,
            maxOccurs: 7,
            collection: true,
            elementName: 'AdrLine'
          }]
      }, {
        localName: 'TaxAuthorisation1',
        propertyInfos: [{
            name: 'titl',
            elementName: 'Titl'
          }, {
            name: 'nm',
            elementName: 'Nm'
          }]
      }, {
        localName: 'SupplementaryDataEnvelope1',
        propertyInfos: [{
            name: 'any',
            required: true,
            mixed: false,
            type: 'anyElement'
          }]
      }, {
        localName: 'TaxInformation6',
        propertyInfos: [{
            name: 'cdtr',
            elementName: 'Cdtr',
            typeInfo: '.TaxParty1'
          }, {
            name: 'dbtr',
            elementName: 'Dbtr',
            typeInfo: '.TaxParty2'
          }, {
            name: 'admstnZn',
            elementName: 'AdmstnZn'
          }, {
            name: 'refNb',
            elementName: 'RefNb'
          }, {
            name: 'mtd',
            elementName: 'Mtd'
          }, {
            name: 'ttlTaxblBaseAmt',
            elementName: 'TtlTaxblBaseAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'ttlTaxAmt',
            elementName: 'TtlTaxAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'dt',
            elementName: 'Dt',
            typeInfo: 'Date'
          }, {
            name: 'seqNb',
            elementName: 'SeqNb',
            typeInfo: 'Decimal'
          }, {
            name: 'rcrd',
            minOccurs: 0,
            collection: true,
            elementName: 'Rcrd',
            typeInfo: '.TaxRecord2'
          }]
      }, {
        localName: 'TaxRecordDetails2',
        propertyInfos: [{
            name: 'prd',
            elementName: 'Prd',
            typeInfo: '.TaxPeriod2'
          }, {
            name: 'amt',
            required: true,
            elementName: 'Amt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }]
      }, {
        localName: 'Purpose2Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'StructuredRegulatoryReporting3',
        propertyInfos: [{
            name: 'tp',
            elementName: 'Tp'
          }, {
            name: 'dt',
            elementName: 'Dt',
            typeInfo: 'Date'
          }, {
            name: 'ctry',
            elementName: 'Ctry'
          }, {
            name: 'cd',
            elementName: 'Cd'
          }, {
            name: 'amt',
            elementName: 'Amt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'inf',
            minOccurs: 0,
            collection: true,
            elementName: 'Inf'
          }]
      }, {
        localName: 'RemittanceLocation4',
        propertyInfos: [{
            name: 'rmtId',
            elementName: 'RmtId'
          }, {
            name: 'rmtLctnDtls',
            minOccurs: 0,
            collection: true,
            elementName: 'RmtLctnDtls',
            typeInfo: '.RemittanceLocationDetails1'
          }]
      }, {
        localName: 'GarnishmentType1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'CreditorReferenceInformation2',
        propertyInfos: [{
            name: 'tp',
            elementName: 'Tp',
            typeInfo: '.CreditorReferenceType2'
          }, {
            name: 'ref',
            elementName: 'Ref'
          }]
      }, {
        localName: 'Party34Choice',
        propertyInfos: [{
            name: 'orgId',
            required: true,
            elementName: 'OrgId',
            typeInfo: '.OrganisationIdentification8'
          }, {
            name: 'prvtId',
            required: true,
            elementName: 'PrvtId',
            typeInfo: '.PersonIdentification13'
          }]
      }, {
        localName: 'CategoryPurpose1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'Garnishment2',
        propertyInfos: [{
            name: 'tp',
            required: true,
            elementName: 'Tp',
            typeInfo: '.GarnishmentType1'
          }, {
            name: 'grnshee',
            elementName: 'Grnshee',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'grnshmtAdmstr',
            elementName: 'GrnshmtAdmstr',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'refNb',
            elementName: 'RefNb'
          }, {
            name: 'dt',
            elementName: 'Dt',
            typeInfo: 'Date'
          }, {
            name: 'rmtdAmt',
            elementName: 'RmtdAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'fmlyMdclInsrncInd',
            elementName: 'FmlyMdclInsrncInd',
            typeInfo: 'Boolean'
          }, {
            name: 'mplyeeTermntnInd',
            elementName: 'MplyeeTermntnInd',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'CreditorReferenceType2',
        propertyInfos: [{
            name: 'cdOrPrtry',
            required: true,
            elementName: 'CdOrPrtry',
            typeInfo: '.CreditorReferenceType1Choice'
          }, {
            name: 'issr',
            elementName: 'Issr'
          }]
      }, {
        localName: 'DiscountAmountType1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'CreditorReferenceType1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'FIToFICustomerCreditTransferV07',
        propertyInfos: [{
            name: 'grpHdr',
            required: true,
            elementName: 'GrpHdr',
            typeInfo: '.GroupHeader70'
          }, {
            name: 'cdtTrfTxInf',
            required: true,
            collection: true,
            elementName: 'CdtTrfTxInf',
            typeInfo: '.CreditTransferTransaction30'
          }, {
            name: 'splmtryData',
            minOccurs: 0,
            collection: true,
            elementName: 'SplmtryData',
            typeInfo: '.SupplementaryData1'
          }]
      }, {
        localName: 'FinancialIdentificationSchemeName1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'GenericFinancialIdentification1',
        propertyInfos: [{
            name: 'id',
            required: true,
            elementName: 'Id'
          }, {
            name: 'schmeNm',
            elementName: 'SchmeNm',
            typeInfo: '.FinancialIdentificationSchemeName1Choice'
          }, {
            name: 'issr',
            elementName: 'Issr'
          }]
      }, {
        localName: 'BranchData2',
        propertyInfos: [{
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'nm',
            elementName: 'Nm'
          }, {
            name: 'pstlAdr',
            elementName: 'PstlAdr',
            typeInfo: '.PostalAddress6'
          }]
      }, {
        localName: 'RegulatoryAuthority2',
        propertyInfos: [{
            name: 'nm',
            elementName: 'Nm'
          }, {
            name: 'ctry',
            elementName: 'Ctry'
          }]
      }, {
        localName: 'FinancialInstitutionIdentification8',
        propertyInfos: [{
            name: 'bicfi',
            elementName: 'BICFI'
          }, {
            name: 'clrSysMmbId',
            elementName: 'ClrSysMmbId',
            typeInfo: '.ClearingSystemMemberIdentification2'
          }, {
            name: 'nm',
            elementName: 'Nm'
          }, {
            name: 'pstlAdr',
            elementName: 'PstlAdr',
            typeInfo: '.PostalAddress6'
          }, {
            name: 'othr',
            elementName: 'Othr',
            typeInfo: '.GenericFinancialIdentification1'
          }]
      }, {
        localName: 'ServiceLevel8Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'InstructionForCreditorAgent1',
        propertyInfos: [{
            name: 'cd',
            elementName: 'Cd'
          }, {
            name: 'instrInf',
            elementName: 'InstrInf'
          }]
      }, {
        localName: 'TaxAmount2',
        propertyInfos: [{
            name: 'rate',
            elementName: 'Rate',
            typeInfo: 'Decimal'
          }, {
            name: 'taxblBaseAmt',
            elementName: 'TaxblBaseAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'ttlAmt',
            elementName: 'TtlAmt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'dtls',
            minOccurs: 0,
            collection: true,
            elementName: 'Dtls',
            typeInfo: '.TaxRecordDetails2'
          }]
      }, {
        localName: 'DocumentLineIdentification1',
        propertyInfos: [{
            name: 'tp',
            elementName: 'Tp',
            typeInfo: '.DocumentLineType1'
          }, {
            name: 'nb',
            elementName: 'Nb'
          }, {
            name: 'rltdDt',
            elementName: 'RltdDt',
            typeInfo: 'Date'
          }]
      }, {
        localName: 'CashAccountType2Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'SupplementaryData1',
        propertyInfos: [{
            name: 'plcAndNm',
            elementName: 'PlcAndNm'
          }, {
            name: 'envlp',
            required: true,
            elementName: 'Envlp',
            typeInfo: '.SupplementaryDataEnvelope1'
          }]
      }, {
        localName: 'GenericOrganisationIdentification1',
        propertyInfos: [{
            name: 'id',
            required: true,
            elementName: 'Id'
          }, {
            name: 'schmeNm',
            elementName: 'SchmeNm',
            typeInfo: '.OrganisationIdentificationSchemeName1Choice'
          }, {
            name: 'issr',
            elementName: 'Issr'
          }]
      }, {
        localName: 'DocumentAdjustment1',
        propertyInfos: [{
            name: 'amt',
            required: true,
            elementName: 'Amt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'cdtDbtInd',
            elementName: 'CdtDbtInd'
          }, {
            name: 'rsn',
            elementName: 'Rsn'
          }, {
            name: 'addtlInf',
            elementName: 'AddtlInf'
          }]
      }, {
        localName: 'Charges2',
        propertyInfos: [{
            name: 'amt',
            required: true,
            elementName: 'Amt',
            typeInfo: '.ActiveOrHistoricCurrencyAndAmount'
          }, {
            name: 'agt',
            required: true,
            elementName: 'Agt',
            typeInfo: '.BranchAndFinancialInstitutionIdentification5'
          }]
      }, {
        localName: 'ContactDetails2',
        propertyInfos: [{
            name: 'nmPrfx',
            elementName: 'NmPrfx'
          }, {
            name: 'nm',
            elementName: 'Nm'
          }, {
            name: 'phneNb',
            elementName: 'PhneNb'
          }, {
            name: 'mobNb',
            elementName: 'MobNb'
          }, {
            name: 'faxNb',
            elementName: 'FaxNb'
          }, {
            name: 'emailAdr',
            elementName: 'EmailAdr'
          }, {
            name: 'othr',
            elementName: 'Othr'
          }]
      }, {
        localName: 'ReferredDocumentType3Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'NameAndAddress10',
        propertyInfos: [{
            name: 'nm',
            required: true,
            elementName: 'Nm'
          }, {
            name: 'adr',
            required: true,
            elementName: 'Adr',
            typeInfo: '.PostalAddress6'
          }]
      }, {
        localName: 'TaxParty1',
        propertyInfos: [{
            name: 'taxId',
            elementName: 'TaxId'
          }, {
            name: 'regnId',
            elementName: 'RegnId'
          }, {
            name: 'taxTp',
            elementName: 'TaxTp'
          }]
      }, {
        localName: 'DocumentLineType1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'DocumentLineType1',
        propertyInfos: [{
            name: 'cdOrPrtry',
            required: true,
            elementName: 'CdOrPrtry',
            typeInfo: '.DocumentLineType1Choice'
          }, {
            name: 'issr',
            elementName: 'Issr'
          }]
      }, {
        localName: 'ActiveCurrencyAndAmount',
        propertyInfos: [{
            name: 'value',
            typeInfo: 'Decimal',
            type: 'value'
          }, {
            name: 'ccy',
            required: true,
            attributeName: {
              localPart: 'Ccy'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'GenericAccountIdentification1',
        propertyInfos: [{
            name: 'id',
            required: true,
            elementName: 'Id'
          }, {
            name: 'schmeNm',
            elementName: 'SchmeNm',
            typeInfo: '.AccountSchemeName1Choice'
          }, {
            name: 'issr',
            elementName: 'Issr'
          }]
      }, {
        localName: 'DocumentLineInformation1',
        propertyInfos: [{
            name: 'id',
            required: true,
            collection: true,
            elementName: 'Id',
            typeInfo: '.DocumentLineIdentification1'
          }, {
            name: 'desc',
            elementName: 'Desc'
          }, {
            name: 'amt',
            elementName: 'Amt',
            typeInfo: '.RemittanceAmount3'
          }]
      }, {
        localName: 'StructuredRemittanceInformation15',
        propertyInfos: [{
            name: 'rfrdDocInf',
            minOccurs: 0,
            collection: true,
            elementName: 'RfrdDocInf',
            typeInfo: '.ReferredDocumentInformation7'
          }, {
            name: 'rfrdDocAmt',
            elementName: 'RfrdDocAmt',
            typeInfo: '.RemittanceAmount2'
          }, {
            name: 'cdtrRefInf',
            elementName: 'CdtrRefInf',
            typeInfo: '.CreditorReferenceInformation2'
          }, {
            name: 'invcr',
            elementName: 'Invcr',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'invcee',
            elementName: 'Invcee',
            typeInfo: '.PartyIdentification125'
          }, {
            name: 'taxRmt',
            elementName: 'TaxRmt',
            typeInfo: '.TaxInformation7'
          }, {
            name: 'grnshmtRmt',
            elementName: 'GrnshmtRmt',
            typeInfo: '.Garnishment2'
          }, {
            name: 'addtlRmtInf',
            minOccurs: 0,
            maxOccurs: 3,
            collection: true,
            elementName: 'AddtlRmtInf'
          }]
      }, {
        localName: 'TaxRecord2',
        propertyInfos: [{
            name: 'tp',
            elementName: 'Tp'
          }, {
            name: 'ctgy',
            elementName: 'Ctgy'
          }, {
            name: 'ctgyDtls',
            elementName: 'CtgyDtls'
          }, {
            name: 'dbtrSts',
            elementName: 'DbtrSts'
          }, {
            name: 'certId',
            elementName: 'CertId'
          }, {
            name: 'frmsCd',
            elementName: 'FrmsCd'
          }, {
            name: 'prd',
            elementName: 'Prd',
            typeInfo: '.TaxPeriod2'
          }, {
            name: 'taxAmt',
            elementName: 'TaxAmt',
            typeInfo: '.TaxAmount2'
          }, {
            name: 'addtlInf',
            elementName: 'AddtlInf'
          }]
      }, {
        localName: 'GarnishmentType1',
        propertyInfos: [{
            name: 'cdOrPrtry',
            required: true,
            elementName: 'CdOrPrtry',
            typeInfo: '.GarnishmentType1Choice'
          }, {
            name: 'issr',
            elementName: 'Issr'
          }]
      }, {
        localName: 'Document',
        propertyInfos: [{
            name: 'fiToFICstmrCdtTrf',
            required: true,
            elementName: 'FIToFICstmrCdtTrf',
            typeInfo: '.FIToFICustomerCreditTransferV07'
          }]
      }, {
        localName: 'OrganisationIdentificationSchemeName1Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'BranchAndFinancialInstitutionIdentification5',
        propertyInfos: [{
            name: 'finInstnId',
            required: true,
            elementName: 'FinInstnId',
            typeInfo: '.FinancialInstitutionIdentification8'
          }, {
            name: 'brnchId',
            elementName: 'BrnchId',
            typeInfo: '.BranchData2'
          }]
      }, {
        localName: 'SettlementTimeRequest2',
        propertyInfos: [{
            name: 'clsTm',
            elementName: 'CLSTm',
            typeInfo: 'Time'
          }, {
            name: 'tillTm',
            elementName: 'TillTm',
            typeInfo: 'Time'
          }, {
            name: 'frTm',
            elementName: 'FrTm',
            typeInfo: 'Time'
          }, {
            name: 'rjctTm',
            elementName: 'RjctTm',
            typeInfo: 'Time'
          }]
      }, {
        localName: 'RegulatoryReporting3',
        propertyInfos: [{
            name: 'dbtCdtRptgInd',
            elementName: 'DbtCdtRptgInd'
          }, {
            name: 'authrty',
            elementName: 'Authrty',
            typeInfo: '.RegulatoryAuthority2'
          }, {
            name: 'dtls',
            minOccurs: 0,
            collection: true,
            elementName: 'Dtls',
            typeInfo: '.StructuredRegulatoryReporting3'
          }]
      }, {
        localName: 'ClearingSystemIdentification2Choice',
        propertyInfos: [{
            name: 'cd',
            required: true,
            elementName: 'Cd'
          }, {
            name: 'prtry',
            required: true,
            elementName: 'Prtry'
          }]
      }, {
        localName: 'DateAndPlaceOfBirth1',
        propertyInfos: [{
            name: 'birthDt',
            required: true,
            elementName: 'BirthDt',
            typeInfo: 'Date'
          }, {
            name: 'prvcOfBirth',
            elementName: 'PrvcOfBirth'
          }, {
            name: 'cityOfBirth',
            required: true,
            elementName: 'CityOfBirth'
          }, {
            name: 'ctryOfBirth',
            required: true,
            elementName: 'CtryOfBirth'
          }]
      }, {
        localName: 'ClearingSystemMemberIdentification2',
        propertyInfos: [{
            name: 'clrSysId',
            elementName: 'ClrSysId',
            typeInfo: '.ClearingSystemIdentification2Choice'
          }, {
            name: 'mmbId',
            required: true,
            elementName: 'MmbId'
          }]
      }, {
        localName: 'SettlementDateTimeIndication1',
        propertyInfos: [{
            name: 'dbtDtTm',
            elementName: 'DbtDtTm',
            typeInfo: 'DateTime'
          }, {
            name: 'cdtDtTm',
            elementName: 'CdtDtTm',
            typeInfo: 'DateTime'
          }]
      }, {
        type: 'enumInfo',
        localName: 'Instruction4Code',
        values: ['PHOA', 'TELA']
      }, {
        type: 'enumInfo',
        localName: 'DocumentType6Code',
        values: ['MSIN', 'CNFA', 'DNFA', 'CINV', 'CREN', 'DEBN', 'HIRI', 'SBIN', 'CMCN', 'SOAC', 'DISP', 'BOLD', 'VCHR', 'AROI', 'TSUT', 'PUOR']
      }, {
        type: 'enumInfo',
        localName: 'Priority2Code',
        values: ['HIGH', 'NORM']
      }, {
        type: 'enumInfo',
        localName: 'SettlementMethod1Code',
        values: ['INDA', 'INGA', 'COVE', 'CLRG']
      }, {
        type: 'enumInfo',
        localName: 'ClearingChannel2Code',
        values: ['RTGS', 'RTNS', 'MPNS', 'BOOK']
      }, {
        type: 'enumInfo',
        localName: 'ChargeBearerType1Code',
        values: ['DEBT', 'CRED', 'SHAR', 'SLEV']
      }, {
        type: 'enumInfo',
        localName: 'AddressType2Code',
        values: ['ADDR', 'PBOX', 'HOME', 'BIZZ', 'MLTO', 'DLVY']
      }, {
        type: 'enumInfo',
        localName: 'CreditDebitCode',
        values: ['CRDT', 'DBIT']
      }, {
        type: 'enumInfo',
        localName: 'TaxRecordPeriod1Code',
        values: ['MM01', 'MM02', 'MM03', 'MM04', 'MM05', 'MM06', 'MM07', 'MM08', 'MM09', 'MM10', 'MM11', 'MM12', 'QTR1', 'QTR2', 'QTR3', 'QTR4', 'HLF1', 'HLF2']
      }, {
        type: 'enumInfo',
        localName: 'DocumentType3Code',
        values: ['RADM', 'RPIN', 'FXDR', 'DISP', 'PUOR', 'SCOR']
      }, {
        type: 'enumInfo',
        localName: 'NamePrefix1Code',
        values: ['DOCT', 'MIST', 'MISS', 'MADM']
      }, {
        type: 'enumInfo',
        localName: 'Priority3Code',
        values: ['URGT', 'HIGH', 'NORM']
      }, {
        type: 'enumInfo',
        localName: 'RegulatoryReportingType1Code',
        values: ['CRED', 'DEBT', 'BOTH']
      }, {
        type: 'enumInfo',
        localName: 'RemittanceLocationMethod2Code',
        values: ['FAXI', 'EDIC', 'URID', 'EMAL', 'POST', 'SMSM']
      }, {
        type: 'enumInfo',
        localName: 'Instruction3Code',
        values: ['CHQB', 'HOLD', 'PHOB', 'TELB']
      }],
    elementInfos: [{
        elementName: 'Document',
        typeInfo: '.Document'
      }]
  };
  return {
    pacs008: pacs008
  };
};
if (typeof define === 'function' && define.amd) {
  define([], pacs008_Module_Factory);
}
else {
  var pacs008_Module = pacs008_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.pacs008 = pacs008_Module.pacs008;
  }
  else {
    var pacs008 = pacs008_Module.pacs008;
  }
}